/*
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MusicDslStandaloneSetup extends MusicDslStandaloneSetupGenerated {

	public static void doSetup() {
		new MusicDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
