/*
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.ide;


/**
 * Use this class to register ide components.
 */
public class MusicDslIdeModule extends AbstractMusicDslIdeModule {
}
