/*
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.mydsl.ide.contentassist.antlr.internal.InternalMusicDslParser;
import org.xtext.example.mydsl.services.MusicDslGrammarAccess;

public class MusicDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MusicDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MusicDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getStaffElementAccess().getAlternatives(), "rule__StaffElement__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getClefTypeAccess().getAlternatives(), "rule__ClefType__Alternatives");
			builder.put(grammarAccess.getRestTypeAccess().getAlternatives(), "rule__RestType__Alternatives");
			builder.put(grammarAccess.getRepetitionTypeAccess().getAlternatives(), "rule__RepetitionType__Alternatives");
			builder.put(grammarAccess.getNoteNameAccess().getAlternatives(), "rule__NoteName__Alternatives");
			builder.put(grammarAccess.getNoteTypeAccess().getAlternatives(), "rule__NoteType__Alternatives");
			builder.put(grammarAccess.getAccidentalTypeAccess().getAlternatives(), "rule__AccidentalType__Alternatives");
			builder.put(grammarAccess.getSlurTypeAccess().getAlternatives(), "rule__SlurType__Alternatives");
			builder.put(grammarAccess.getArticulationTypeAccess().getAlternatives(), "rule__ArticulationType__Alternatives");
			builder.put(grammarAccess.getOrnamentTypeAccess().getAlternatives(), "rule__OrnamentType__Alternatives");
			builder.put(grammarAccess.getCompositionAccess().getGroup(), "rule__Composition__Group__0");
			builder.put(grammarAccess.getCompositionAccess().getGroup_4(), "rule__Composition__Group_4__0");
			builder.put(grammarAccess.getCompositionAccess().getGroup_5(), "rule__Composition__Group_5__0");
			builder.put(grammarAccess.getCompositionAccess().getGroup_6(), "rule__Composition__Group_6__0");
			builder.put(grammarAccess.getCompositionAccess().getGroup_7(), "rule__Composition__Group_7__0");
			builder.put(grammarAccess.getCompositionAccess().getGroup_9(), "rule__Composition__Group_9__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getStaffAccess().getGroup(), "rule__Staff__Group__0");
			builder.put(grammarAccess.getStaffAccess().getGroup_6(), "rule__Staff__Group_6__0");
			builder.put(grammarAccess.getStaffAccess().getGroup_9(), "rule__Staff__Group_9__0");
			builder.put(grammarAccess.getStaffAccess().getGroup_9_1(), "rule__Staff__Group_9_1__0");
			builder.put(grammarAccess.getClefAccess().getGroup(), "rule__Clef__Group__0");
			builder.put(grammarAccess.getTimeSignatureAccess().getGroup(), "rule__TimeSignature__Group__0");
			builder.put(grammarAccess.getMeasureAccess().getGroup(), "rule__Measure__Group__0");
			builder.put(grammarAccess.getMeasureAccess().getGroup_4(), "rule__Measure__Group_4__0");
			builder.put(grammarAccess.getMeasureAccess().getGroup_4_1(), "rule__Measure__Group_4_1__0");
			builder.put(grammarAccess.getMeasureAccess().getGroup_5(), "rule__Measure__Group_5__0");
			builder.put(grammarAccess.getMeasureAccess().getGroup_5_1(), "rule__Measure__Group_5_1__0");
			builder.put(grammarAccess.getMeasureAccess().getGroup_6(), "rule__Measure__Group_6__0");
			builder.put(grammarAccess.getMeasureAccess().getGroup_6_1(), "rule__Measure__Group_6_1__0");
			builder.put(grammarAccess.getRestAccess().getGroup(), "rule__Rest__Group__0");
			builder.put(grammarAccess.getRepetitionAccess().getGroup(), "rule__Repetition__Group__0");
			builder.put(grammarAccess.getNoteAccess().getGroup(), "rule__Note__Group__0");
			builder.put(grammarAccess.getNoteAccess().getGroup_4(), "rule__Note__Group_4__0");
			builder.put(grammarAccess.getNoteAccess().getGroup_5(), "rule__Note__Group_5__0");
			builder.put(grammarAccess.getNoteAccess().getGroup_6(), "rule__Note__Group_6__0");
			builder.put(grammarAccess.getNoteAccess().getGroup_7(), "rule__Note__Group_7__0");
			builder.put(grammarAccess.getNoteAccess().getGroup_8(), "rule__Note__Group_8__0");
			builder.put(grammarAccess.getNoteAccess().getGroup_9(), "rule__Note__Group_9__0");
			builder.put(grammarAccess.getNoteAccess().getGroup_10(), "rule__Note__Group_10__0");
			builder.put(grammarAccess.getNoteAccess().getGroup_14(), "rule__Note__Group_14__0");
			builder.put(grammarAccess.getNoteAccess().getGroup_14_1(), "rule__Note__Group_14_1__0");
			builder.put(grammarAccess.getNotationAccess().getGroup(), "rule__Notation__Group__0");
			builder.put(grammarAccess.getNotationAccess().getGroup_2(), "rule__Notation__Group_2__0");
			builder.put(grammarAccess.getNotationAccess().getGroup_3(), "rule__Notation__Group_3__0");
			builder.put(grammarAccess.getNotationAccess().getGroup_4(), "rule__Notation__Group_4__0");
			builder.put(grammarAccess.getCompositionAccess().getNameAssignment_2(), "rule__Composition__NameAssignment_2");
			builder.put(grammarAccess.getCompositionAccess().getAuthorAssignment_4_1(), "rule__Composition__AuthorAssignment_4_1");
			builder.put(grammarAccess.getCompositionAccess().getInstrumentAssignment_5_1(), "rule__Composition__InstrumentAssignment_5_1");
			builder.put(grammarAccess.getCompositionAccess().getTonalityAssignment_6_1(), "rule__Composition__TonalityAssignment_6_1");
			builder.put(grammarAccess.getCompositionAccess().getSoundTempoAssignment_7_1(), "rule__Composition__SoundTempoAssignment_7_1");
			builder.put(grammarAccess.getCompositionAccess().getStaffAssignment_8(), "rule__Composition__StaffAssignment_8");
			builder.put(grammarAccess.getCompositionAccess().getStaffAssignment_9_1(), "rule__Composition__StaffAssignment_9_1");
			builder.put(grammarAccess.getStaffAccess().getStaffNumberAssignment_2(), "rule__Staff__StaffNumberAssignment_2");
			builder.put(grammarAccess.getStaffAccess().getClefAssignment_5(), "rule__Staff__ClefAssignment_5");
			builder.put(grammarAccess.getStaffAccess().getKeyAssignment_6_1(), "rule__Staff__KeyAssignment_6_1");
			builder.put(grammarAccess.getStaffAccess().getTimeAssignment_8(), "rule__Staff__TimeAssignment_8");
			builder.put(grammarAccess.getStaffAccess().getElementsAssignment_9_0(), "rule__Staff__ElementsAssignment_9_0");
			builder.put(grammarAccess.getStaffAccess().getElementsAssignment_9_1_1(), "rule__Staff__ElementsAssignment_9_1_1");
			builder.put(grammarAccess.getClefAccess().getTypeAssignment_1(), "rule__Clef__TypeAssignment_1");
			builder.put(grammarAccess.getTimeSignatureAccess().getBeatAssignment_1(), "rule__TimeSignature__BeatAssignment_1");
			builder.put(grammarAccess.getTimeSignatureAccess().getBeatTypeAssignment_4(), "rule__TimeSignature__BeatTypeAssignment_4");
			builder.put(grammarAccess.getKeyAccess().getFifthsAssignment(), "rule__Key__FifthsAssignment");
			builder.put(grammarAccess.getMeasureAccess().getMeasureNumberAssignment_2(), "rule__Measure__MeasureNumberAssignment_2");
			builder.put(grammarAccess.getMeasureAccess().getRepetitionAssignment_4_0(), "rule__Measure__RepetitionAssignment_4_0");
			builder.put(grammarAccess.getMeasureAccess().getRepetitionAssignment_4_1_1(), "rule__Measure__RepetitionAssignment_4_1_1");
			builder.put(grammarAccess.getMeasureAccess().getRestAssignment_5_0(), "rule__Measure__RestAssignment_5_0");
			builder.put(grammarAccess.getMeasureAccess().getRestAssignment_5_1_1(), "rule__Measure__RestAssignment_5_1_1");
			builder.put(grammarAccess.getMeasureAccess().getNoteAssignment_6_0(), "rule__Measure__NoteAssignment_6_0");
			builder.put(grammarAccess.getMeasureAccess().getNoteAssignment_6_1_1(), "rule__Measure__NoteAssignment_6_1_1");
			builder.put(grammarAccess.getRestAccess().getTypeAssignment_2(), "rule__Rest__TypeAssignment_2");
			builder.put(grammarAccess.getRepetitionAccess().getTypeAssignment_2(), "rule__Repetition__TypeAssignment_2");
			builder.put(grammarAccess.getNoteAccess().getNameAssignment_2(), "rule__Note__NameAssignment_2");
			builder.put(grammarAccess.getNoteAccess().getTypeAssignment_4_1(), "rule__Note__TypeAssignment_4_1");
			builder.put(grammarAccess.getNoteAccess().getDurationAssignment_5_1(), "rule__Note__DurationAssignment_5_1");
			builder.put(grammarAccess.getNoteAccess().getOctaveAssignment_6_1(), "rule__Note__OctaveAssignment_6_1");
			builder.put(grammarAccess.getNoteAccess().getVoiceAssignment_7_1(), "rule__Note__VoiceAssignment_7_1");
			builder.put(grammarAccess.getNoteAccess().getDynamicAssignment_8_1(), "rule__Note__DynamicAssignment_8_1");
			builder.put(grammarAccess.getNoteAccess().getAccidentalAssignment_9_1(), "rule__Note__AccidentalAssignment_9_1");
			builder.put(grammarAccess.getNoteAccess().getLyricsAssignment_10_1(), "rule__Note__LyricsAssignment_10_1");
			builder.put(grammarAccess.getNoteAccess().getFermataAssignment_11(), "rule__Note__FermataAssignment_11");
			builder.put(grammarAccess.getNoteAccess().getDotAssignment_12(), "rule__Note__DotAssignment_12");
			builder.put(grammarAccess.getNoteAccess().getChordAssignment_13(), "rule__Note__ChordAssignment_13");
			builder.put(grammarAccess.getNoteAccess().getNotationAssignment_14_0(), "rule__Note__NotationAssignment_14_0");
			builder.put(grammarAccess.getNoteAccess().getNotationAssignment_14_1_1(), "rule__Note__NotationAssignment_14_1_1");
			builder.put(grammarAccess.getNotationAccess().getArticulationAssignment_2_1(), "rule__Notation__ArticulationAssignment_2_1");
			builder.put(grammarAccess.getNotationAccess().getOrnamentAssignment_3_1(), "rule__Notation__OrnamentAssignment_3_1");
			builder.put(grammarAccess.getNotationAccess().getSlurAssignment_4_1(), "rule__Notation__SlurAssignment_4_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MusicDslGrammarAccess grammarAccess;

	@Override
	protected InternalMusicDslParser createParser() {
		InternalMusicDslParser result = new InternalMusicDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MusicDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MusicDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
